### ISSUE TITLE
How high is the crane?

### ISSUE THREAD

**Issue by tpoomlmly** [sourcebots/smallpeice-rules#20]

**Comment by tpoomlmly** [comment]
It's 1.5m but the rules don't say

**Comment by tpoomlmly** [comment]
@jefftheprogrammer tells me it's actually 1.6m

**Comment by WillB97** [comment]
It depends where on the crane you are measuring to. The crane was positioned so that the bottom of the hook is 1.5 meters above the floor when fully raised.
